trigger:
- main

parameters:
- name: environment
  type: string
  default: Dev
  values:
  - Dev
  - Prod

- name: deployNetwork
  type: boolean
  default: true

- name: deployData
  type: boolean
  default: false

variables:
  bk_rg: *
  bk_sa: *
  bk_container: tfstate
  svc_conn: AD-TF

# =========================================================
# STAGE 1 - PLAN
# =========================================================
stages:
- stage: Plan
  displayName: Terraform Plan

  jobs:

  - job: Init
    displayName: Initialize
    pool:
      name: Linux-SHA-Pool
    steps:
    - script: echo "Initializing Terraform deployment..."

  # ---------------- NETWORK PLAN ----------------
  - ${{ if eq(parameters.deployNetwork, true) }}:
    - template: templates/plan.yml
      parameters:
        plan_environment: ${{ parameters.environment }}
        workload: Network
        serviceConnection: $(svc_conn)
        resourceGroup: $(bk_rg)
        storageAccount: $(bk_sa)
        containerName: $(bk_container)
        dependsOn: ['Init']

  # ---------------- DATA PLAN ----------------
  - ${{ if eq(parameters.deployData, true) }}:
    - template: templates/plan.yml
      parameters:
        plan_environment: ${{ parameters.environment }}
        workload: Data
        serviceConnection: $(svc_conn)
        resourceGroup: $(bk_rg)
        storageAccount: $(bk_sa)
        containerName: $(bk_container)
        dependsOn: ['Init']


# =========================================================
# STAGE 2 - APPLY (Approval here)
# =========================================================
- stage: Apply
  displayName: Terraform Apply
  dependsOn: Plan

  jobs:

  # ---------------- NETWORK APPLY ----------------
  - ${{ if eq(parameters.deployNetwork, true) }}:
    - template: templates/apply.yml
      parameters:
        environment: ${{ parameters.environment }}
        environmentName: ${{ parameters.environment }}-apply
        workload: Network
        serviceConnection: $(svc_conn)
        resourceGroup: $(bk_rg)
        storageAccount: $(bk_sa)
        containerName: $(bk_container)
        dependsOn: []

  # ---------------- DATA APPLY ----------------
  - ${{ if eq(parameters.deployData, true) }}:
    - template: templates/apply.yml
      parameters:
        environment: ${{ parameters.environment }}
        environmentName: ${{ parameters.environment }}-apply
        workload: Data
        serviceConnection: $(svc_conn)
        resourceGroup: $(bk_rg)
        storageAccount: $(bk_sa)
        containerName: $(bk_container)
        dependsOn: []
